### ISSUE TITLE
License violation spotted - another organization stole your project

### ISSUE THREAD

**Issue by HarukaMa** [Picolab/node-sovrin-did#4]
The project, https://github.com/benchlab/KeplerKeys, copied your project without attribution and violated your license by claiming the author.

I've done a diff between the projects which could be found [here](https://pastebin.com/K7MDs4g9), if you want to take a look at.

I'd suggest you talk to the project directly or report it to GitHub to takedown the violating repository.

**Comment by farskipper** [comment]
@JaredRiceSr why?
